AzureMonitorMetrics:
  KubeStateMetrics:
# Uncomment the below 2 settings if you want to pass in the labels and/or annotations
    #MetricLabelsAllowlist: "testlabel=[.*]"
    #MetricAnnotationsAllowList: ""
    ImageRepository: "/oss/kubernetes/kube-state-metrics"
# Kube-state-metrics ImageTag - 2.8.1, corresponds to chart version - 4.32.0
    ImageTag: "v2.8.1"
    Collectors:
      - certificatesigningrequests
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - leases
      - limitranges
      - mutatingwebhookconfigurations
      - namespaces
      - networkpolicies
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - poddisruptionbudgets
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - secrets
      - services
      - statefulsets
      - storageclasses
      - validatingwebhookconfigurations
      - volumeattachments
  ImageRepository: /azuremonitor/containerinsights/ciprod/prometheus-collector/images
  ImageTag: 6.7.0-main-05-04-2023-4450ad10
  ImageTagWin: 6.7.0-main-05-04-2023-4450ad10-win
  # The below 2 settings are not Azure Monitor Metrics adapter chart. They are substituted in a different manner.
  # Please update these with the latest ones from here so that you get the image that is currently deployed by the AKS RP -
  # Repository: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/addon-charts/azure-monitor-metrics-addon/templates/ama-metrics-daemonset.yaml&version=GBrashmi/prom-addon-arm64&line=136&lineEnd=136&lineStartColumn=56&lineEndColumn=85&lineStyle=plain&_a=contents
  # ImageTag: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/kube-control-plane/templates/_images.tpl&version=GBrashmi/prom-addon-arm64&line=530&lineEnd=530&lineStartColumn=28&lineEndColumn=53&lineStyle=plain&_a=contents
  AddonTokenAdapter:
    ImageRepository: "/aks/msi/addon-token-adapter"
    ImageTag: "master.221118.2"
    ImageRepositoryWin: "/aks/hcp/addon-token-adapter"
    ImageTagWin: "20230120winbeta"
  # Do not change the below settings. They are reserved for Arc Autonomous
  isArcACluster: false
  arcAutonomousSettings:
    customRegionalEndpoint: ""
    customGlobalEndpoint: ""
    customResourceEndpoint: ""
global:
  commonGlobals:
    CloudEnvironment: "azurepubliccloud"
    Region: eastus2euap 
    Customer:
      # AzureResourceID: /subscriptions/8643025a-c059-4a48-85d0-d76f51d63a74/resourcegroups/shmalfatcanary/providers/Microsoft.ContainerService/managedClusters/shmalfatcanary 
      AzureResourceID: /subscriptions/18153b17-4e27-4b58-863e-f8105b8892a2/resourceGroups/shmalfatebld73815787/providers/Microsoft.ContainerService/managedClusters/shmalfat-test-1 

# For ARC backdoor testing
Azure:
  Extension:
    Name: azuremonitor-metrics
  Cluster:
    ResourceId: "${ARC_RESOURCE_ID}"
    Region: "${ARC_REGION}"
  proxySettings:
    isProxyEnabled: "false"
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
    proxyCert: ""
  Identity:
      MSIAdapterYaml: |-
        - name: EXTENSION_ARMID
          value: ${ARC_RESOURCE_ID}/providers/Microsoft.KubernetesConfiguration/extensions/azuremonitor-metrics
        - name: EXTENSION_NAME
          value: azuremonitor-metrics
        - name: CLUSTER_IDENTITY
          value: "false"
        - name: CLUSTER_TYPE
          value:  ConnectedClusters
        - name: MANAGED_IDENTITY_AUTH
          value: "true"
        - name: TEST_MODE
          value: "false"
        - name: TEST_FILE
          value: "/data/token"
        image: "mcr.microsoft.com/azurearck8s/msi-adapter:1.0.4"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9999
            scheme: "HTTP"
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi
prometheus-node-exporter:
  service:
    port: 9110
    targetPort: 9110
